CREATE TABLE platform_notification (
  id UUID PRIMARY KEY,
  seq BIGINT GENERATED ALWAYS AS IDENTITY UNIQUE,
  account_id UUID NOT NULL REFERENCES platform_account (id) ON DELETE CASCADE,
  kind VARCHAR(64) NOT NULL,
  params TEXT NOT NULL,
  link VARCHAR(500),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  read_at TIMESTAMP WITH TIME ZONE
)
