export const DELIVERED_DOCUMENTS = [
  'adoption.md',
  'project-process.md',
  'tickets.md',
  'naming.md',
  'build.md',
  'quality-checks.md',
  'dependencies.md',
  'deployment.md',
  'release-cycle.md',
  'api-errors.md',
  'code-design.md',
  'component-replacement.md',
  'data-access.md',
  'configuration.md',
  'secret-storage.md',
  'compatibility.md',
  'agent-work.md',
  'code-comments.md',
  'code-clock.md',
  'java-clock.md',
  'java-modules.md',
  'java-naming.md',
  'rust-clock.md',
  'rust-modules.md',
  'rust-naming.md',
  'typescript-clock.md',
  'client-modals.md',
  'client-actions.md',
  'project-rules.md',
  'rule-distribution.md',
  'terminology.md',
];

// REQ-ADOPTION-016
export const CORE_ONLY_DOCUMENTS = {
  'persistence.md': 'контракт кода самого ядра: каталог запросов, загрузчик, порты',
  'publishing.md': 'правила версионирования и публикации артефактов ядра',
};
